ci:
    autofix_prs: false
    autoupdate_schedule: weekly

repos:
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.1
  hooks:
    - id: check-github-workflows
